services:
  redis:
    container_name: redis
    env_file:
      - redis.env
    image: redis:8.0.4-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - agent_redis:/data
    networks:
      - my_network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - agent_qdrant:/qdrant/storage:z
    restart: always
    networks:
      - my_network

volumes:
  agent_redis:
  agent_qdrant:

networks:
  my_network:
    driver: bridge