services:
  redis:
    container_name: redis
    env_file:
      - redis.env
    image: redis:8.0.4-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - agent_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - agent_qdrant:/qdrant/storage:z
    restart: always

  calendar:
    container_name: calendar
    build: ./servers/calendar
    restart: always
    ports:
      - "8001:8001"

  sheet:
    container_name: sheet
    build: ./servers/sheet
    restart: always
    ports:
      - "8003:8003"
  
  mail:
    container_name: mail
    build: ./servers/mail
    restart: always
    ports:
      - "8002:8002"

  agent:
    container_name: agent
    build: .
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env

volumes:
  agent_redis:
  agent_qdrant:
